/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkoutsIndexRouteImport } from './routes/workouts/index'
import { Route as MyTrainersIndexRouteImport } from './routes/my-trainers/index'
import { Route as HealthIndexRouteImport } from './routes/health/index'
import { Route as ClientsIndexRouteImport } from './routes/clients/index'
import { Route as WorkoutsNewRouteImport } from './routes/workouts/new'
import { Route as SignUpSplatRouteImport } from './routes/sign-up/$'
import { Route as SignInSplatRouteImport } from './routes/sign-in/$'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkoutsIndexRoute = WorkoutsIndexRouteImport.update({
  id: '/workouts/',
  path: '/workouts/',
  getParentRoute: () => rootRouteImport,
} as any)
const MyTrainersIndexRoute = MyTrainersIndexRouteImport.update({
  id: '/my-trainers/',
  path: '/my-trainers/',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthIndexRoute = HealthIndexRouteImport.update({
  id: '/health/',
  path: '/health/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsIndexRoute = ClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkoutsNewRoute = WorkoutsNewRouteImport.update({
  id: '/workouts/new',
  path: '/workouts/new',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpSplatRoute = SignUpSplatRouteImport.update({
  id: '/sign-up/$',
  path: '/sign-up/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInSplatRoute = SignInSplatRouteImport.update({
  id: '/sign-in/$',
  path: '/sign-in/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/onboarding': typeof OnboardingRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/workouts/new': typeof WorkoutsNewRoute
  '/clients/': typeof ClientsIndexRoute
  '/health/': typeof HealthIndexRoute
  '/my-trainers/': typeof MyTrainersIndexRoute
  '/workouts/': typeof WorkoutsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/onboarding': typeof OnboardingRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/workouts/new': typeof WorkoutsNewRoute
  '/clients': typeof ClientsIndexRoute
  '/health': typeof HealthIndexRoute
  '/my-trainers': typeof MyTrainersIndexRoute
  '/workouts': typeof WorkoutsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/onboarding': typeof OnboardingRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/workouts/new': typeof WorkoutsNewRoute
  '/clients/': typeof ClientsIndexRoute
  '/health/': typeof HealthIndexRoute
  '/my-trainers/': typeof MyTrainersIndexRoute
  '/workouts/': typeof WorkoutsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/onboarding'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/workouts/new'
    | '/clients/'
    | '/health/'
    | '/my-trainers/'
    | '/workouts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/onboarding'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/workouts/new'
    | '/clients'
    | '/health'
    | '/my-trainers'
    | '/workouts'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/onboarding'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/workouts/new'
    | '/clients/'
    | '/health/'
    | '/my-trainers/'
    | '/workouts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  OnboardingRoute: typeof OnboardingRoute
  SignInSplatRoute: typeof SignInSplatRoute
  SignUpSplatRoute: typeof SignUpSplatRoute
  WorkoutsNewRoute: typeof WorkoutsNewRoute
  ClientsIndexRoute: typeof ClientsIndexRoute
  HealthIndexRoute: typeof HealthIndexRoute
  MyTrainersIndexRoute: typeof MyTrainersIndexRoute
  WorkoutsIndexRoute: typeof WorkoutsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workouts/': {
      id: '/workouts/'
      path: '/workouts'
      fullPath: '/workouts/'
      preLoaderRoute: typeof WorkoutsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-trainers/': {
      id: '/my-trainers/'
      path: '/my-trainers'
      fullPath: '/my-trainers/'
      preLoaderRoute: typeof MyTrainersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health/': {
      id: '/health/'
      path: '/health'
      fullPath: '/health/'
      preLoaderRoute: typeof HealthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/': {
      id: '/clients/'
      path: '/clients'
      fullPath: '/clients/'
      preLoaderRoute: typeof ClientsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workouts/new': {
      id: '/workouts/new'
      path: '/workouts/new'
      fullPath: '/workouts/new'
      preLoaderRoute: typeof WorkoutsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up/$': {
      id: '/sign-up/$'
      path: '/sign-up/$'
      fullPath: '/sign-up/$'
      preLoaderRoute: typeof SignUpSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in/$': {
      id: '/sign-in/$'
      path: '/sign-in/$'
      fullPath: '/sign-in/$'
      preLoaderRoute: typeof SignInSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  OnboardingRoute: OnboardingRoute,
  SignInSplatRoute: SignInSplatRoute,
  SignUpSplatRoute: SignUpSplatRoute,
  WorkoutsNewRoute: WorkoutsNewRoute,
  ClientsIndexRoute: ClientsIndexRoute,
  HealthIndexRoute: HealthIndexRoute,
  MyTrainersIndexRoute: MyTrainersIndexRoute,
  WorkoutsIndexRoute: WorkoutsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
